[project]
name = "embedding"
version = "0.1.0"
description = ""
authors = [
    {name = "王启轩",email = "wangqixuan@icourt.cc"}
]
readme = "README.md"
requires-python = ">=2.7"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
